export const data = [
    {
        name: "Tom and Jery",
        desc: "Comedy",
        image: "img",
        titleImage: "titleImg",
        category: "category",
        language: "English",
        year: 2000,
        video: "video",
        time: '3hr',
        rate: 0,
        numberOfRevews: 0,
        reviews: [],
        casts: [],
    },
    {
        name: "Tom and Jery 2",
        desc: "Comedy",
        image: "img",
        titleImage: "titleImg",
        category: "category",
        language: "English",
        year: 2000,
        video: "video",
        time: '3hr',
        rate: 0,
        numberOfRevews: 0,
        reviews: [],
        casts: [],
    },
    {
        name: "Tom and Jery 3",
        desc: "Comedy",
        image: "img",
        titleImage: "titleImg",
        category: "category",
        language: "English",
        year: 2000,
        video: "video",
        time: '3hr',
        rate: 0,
        numberOfRevews: 0,
        reviews: [],
        casts: [],
    },
]